hardwares:

  spi0:
    type: "spi"
    path: "/dev/spidev0.0"
    speed: 100000
    mode: 1
    bits: 8

  uart0:
    type: "uart"
    path: "/dev/ttyAMA0"
    baudrate: 57600
    read_timeout: 1

  uart1:
    type: "uart"
    path: "/dev/ttyUSB0"
    baudrate: 115200

  tcpuartc:
    type: "tcpuartclient"
    mdns_service: "smoothie.uart"

  pwm0:
    type: "pwm"
    pwm: 12

  pwm1:
    type: "pwm"
    pwm: 13

  i2c1:
    type: "i2c"
    path: "/dev/i2c-1"

  distance_ranging_sensor:
    type: "vl6180x"
    dev: "i2c1"
    address: 0x_29
    scaling: 2

  output_sensor:
    type: "max31856"
    dev: "spi0"
    tc: "T"
    mode: "Automatic"
    sample: "Avg1" # 1, 2, 54, 8, 16

  tank_sensor:
    type: "max31865"
    dev: "spi0"
    wire: "3"
    mode: "Automatic"

  extruder:
    type: "extruder"
    dev: "uart0"

  smoothie:
    type: "smoothie"
    dev: "tcpuartc"

  water_detector:
    type: "water_detector"
    gpio: 16

services:
  web:
    enable: true
    port: 8080
    static_files: "static"
    mongodb:
      # Production
      #url: "mongodb://turingcoffee:turingcoffeepassword@ds021000.mlab.com:21000/turing-coffee"
      #collection: "cookbooknew"
      # For testing
      url: "mongodb+srv://turingcoffee:test12345@cluster0.m5idb.gcp.mongodb.net/testturingcoffee?retryWrites=true&w=majority"
      database: "turing-coffee"
      collections:
        cookbook: "cookbook"
        process: "process"

mdns:
  instance: "TuringCoffee"
  domain: "local."

nats:
  register: true
  service: "nats.io"
  port: 4222
