hardwares:

  spi0:
    type: "spi"
    path: "/dev/spidev0.0"
    speed: 100000
    mode: 1
    bits: 8

  uart0:
    type: "uart"
    path: "/dev/ttyAMA0"
    baudrate: 57600
    read_timeout: 1

  uart1:
    type: "uart"
    path: "/dev/ttyUSB0"
    baudrate: 115200

  uart2:
    type: "uart"
    path: "/dev/ttyUSB0"
    baudrate: 57600
    read_timeout: 1

  tcpuartc:
    type: "tcpuartclient"
    mdns_service: "smoothie.uart"

  pwm0:
    type: "pwm"
    pwm: 12

  pwm1:
    type: "pwm"
    pwm: 13

  i2c1:
    type: "i2c"
    path: "/dev/i2c-1"

  distance_ranging_sensor:
    type: "vl6180x"
    dev: "i2c1"
    address: 0x_29
    scaling: 2

  output_sensor:
    type: "max31856"
    dev: "spi0"
    tc: "T"
    mode: "Automatic"
    sample: "Avg1" # 1, 2, 54, 8, 16

  tank_sensor:
    type: "max31865"
    dev: "spi0"
    wire: "3"
    mode: "Automatic"

  extruder:
    type: "extruder"
    dev: "uart0"

  smoothie:
    type: "smoothie"
    dev: "tcpuartc"

  water_detector:
    type: "water_detector"
    gpio: 16

services:

  output_temp_service:
    enable: false
    scan_interval_ms: 1000
    dev: "output_sensor"

  tank_temp_service:
    enable: true
    scan_interval_ms: 1000
    dev: "tank_sensor"

  tank_meter_service:
    enable: true
    scan_interval_ms: 1000
    dev: "water_detector"

  distance_ranging_service:
    enable: false 
    scan_interval_ms: 1000
    dev: "distance_ranging_sensor"

  replenish_service:
    enable: true
    scan_interval_ms: 1000
    dev: "pwm0"
    duty_cycle: 0.5
    frequency: 120000

  heater:
    enable: true
    scan_interval_ms: 1000
    pwm_dev: "pwm1"
    pid:
      P: 2
      I: 0.25
      D: 1

  barista:
    enable: true
    smoothie: "smoothie"
    extruder: "extruder"
    accumulative_water_volume: 20
    pid:
      P: 0.006
      I: 0.0005
      D: 0.007
    drain_position:
      x: -3
      i: -72 # cannot use 'y' in viper, but don't know why
      z: 230
    default_moving_speed: 5000
    water_per_pulse:
      hot: 0.0025
      cold: 0.0023

  uartserver:
    enable: false
    mdns_service: "smoothie.uart"
    port: 22222
    uartdev: "uart1"

  web:
    enable: true
    port: 8080
    static_files: "static"
    mongodb:
      address: "mongodb+srv://turingcoffee:test12345@turing-coffee.8wnkm.mongodb.net/turing-coffee?retryWrites=true&w=majority"
      database: "turing-coffee"
      collection: "cookbooknew"

mdns:
  instance: "TuringCoffee"
  domain: "local."

nats:
  register: true
  service: "nats.io"
  port: 4222
