hardwares:
  uart0:
    type: "uart"
    path: "/dev/ttyS1"
    baudrate: 115200
    read_timeout: 1

  spi0:
    type: "spi"
    path: "/dev/spidev1.0"
    speed: 100000
    mode: 1
    bits: 8

  spi1:
    type: "spigpio"
    path: ""
    speed: 100000
    mode: 1
    bits: 8
    clk: 0
    mosi: 1
    miso: 2
    cs: 3

  i2c0:
    type: "i2c"
    path: "/dev/i2c-0"

  output_sensor:
    type: "max31856"
    dev: "spi0"
    tc: "T"
    mode: "Automatic"
    sample: "Avg1" # 1, 2, 54, 8, 16

  distance_ranging_sensor:
    type: "vl6180x"
    dev: "i2c0"
    address: 0x_29
    scaling: 1

  thermal_block_sensor:
    type: "max31856"
    dev: "spi1"
    tc: "T"
    mode: "Automatic"
    sample: "Avg1" # 1, 2, 54, 8, 16

  pwm0:
    type: "pwm"
    pwm: 7

services:

  uartserver:
    enable: true
    mdns_service: "smoothie.uart"
    port: 22222
    uartdev: "uart0"

  output_temp_service:
    enable: true
    scan_interval_ms: 2000
    dev: "output_sensor"

  distance_ranging_service:
    enable: true
    scan_interval_ms: 1000
    dev: "distance_ranging_sensor"

  thermal_block_temp:
    enable: true
    scan_interval_ms: 1000
    dev: "thermal_block_sensor"

  thermal_block_heater:
    enable: true
    scan_interval_ms: 1000
    dev: "pwm0"
    pid:
      P: 2
      I: 0.25
      D: 1

mdns:
  instance: "TuringCoffee"
  domain: "local."

nats:
  register: false
  service: "nats.io"
  port: 4222
